# Truck ambulance tensorrt configs

truckamb:
  det_engine_path: tmp/models/yolov8_s_ort.onnx
  cls_engine_path: tmp/models/ambulance_cls.onnx
  cls_max_batch_size: 1
  det_provider: cpu
  cls_provider: cpu
  det_end2end: true
  det_arch: yolov8
  det_pretrained: True
  det_categories: null
  cls_categories: 
    - ambulance
    - car