# main configs

defaults:
  - _self_
  - api: [main_api]
  - engine: [truckamb_trt]
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

# override hydra output directory
hydra:
  run:
    dir: .
  output_subdir: null
